__title__ = 'Streaming_community'
__version__ = 'v0.6.1'
__author__ = 'Ghost6446'
__description__ = 'A command-line program to download film'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2023'